import { Brand, PricingTier, WatchlistItem } from './types';

export const brands: Brand[] = [
  {
    id: 'zara',
    name: 'Zara',
    logo: '👗',
    industry: 'Fast Fashion',
    country: 'Spain',
    esgScore: 62,
    environmentalScore: 55,
    socialScore: 68,
    governanceScore: 64,
    supplyChainTransparency: 58,
    carbonFootprint: 45,
    laborEthics: 60,
    trend: 'up',
    trendValue: 3.2,
    certificates: ['ISO 14001', 'OEKO-TEX'],
    lastUpdated: '2024-01-15',
    sentiment: 65,
    newsHighlights: [
      { title: 'Zara commits to 100% sustainable fabrics by 2030', source: 'Reuters', date: '2024-01-10', sentiment: 'positive' },
      { title: 'Supply chain concerns raised in Bangladesh factories', source: 'The Guardian', date: '2024-01-05', sentiment: 'negative' },
      { title: 'New recycling program launched in EU stores', source: 'Fashion Weekly', date: '2024-01-02', sentiment: 'positive' },
    ],
    history: [
      { month: 'Aug', esg: 55, environmental: 48, social: 60, governance: 58 },
      { month: 'Sep', esg: 56, environmental: 49, social: 61, governance: 59 },
      { month: 'Oct', esg: 58, environmental: 51, social: 63, governance: 60 },
      { month: 'Nov', esg: 59, environmental: 52, social: 65, governance: 61 },
      { month: 'Dec', esg: 60, environmental: 53, social: 66, governance: 62 },
      { month: 'Jan', esg: 62, environmental: 55, social: 68, governance: 64 },
    ],
  },
  {
    id: 'lcw',
    name: 'LC Waikiki',
    logo: '👕',
    industry: 'Fast Fashion',
    country: 'Turkey',
    esgScore: 54,
    environmentalScore: 48,
    socialScore: 58,
    governanceScore: 56,
    supplyChainTransparency: 45,
    carbonFootprint: 40,
    laborEthics: 52,
    trend: 'stable',
    trendValue: 0.5,
    certificates: ['ISO 9001'],
    lastUpdated: '2024-01-14',
    sentiment: 55,
    newsHighlights: [
      { title: 'LC Waikiki expands to 50 new markets', source: 'Bloomberg', date: '2024-01-12', sentiment: 'neutral' },
      { title: 'New organic cotton line receives mixed reviews', source: 'Textile Today', date: '2024-01-08', sentiment: 'neutral' },
    ],
    history: [
      { month: 'Aug', esg: 50, environmental: 44, social: 54, governance: 52 },
      { month: 'Sep', esg: 51, environmental: 45, social: 55, governance: 53 },
      { month: 'Oct', esg: 52, environmental: 46, social: 56, governance: 54 },
      { month: 'Nov', esg: 53, environmental: 47, social: 57, governance: 55 },
      { month: 'Dec', esg: 53, environmental: 47, social: 57, governance: 55 },
      { month: 'Jan', esg: 54, environmental: 48, social: 58, governance: 56 },
    ],
  },
  {
    id: 'patagonia',
    name: 'Patagonia',
    logo: '🏔️',
    industry: 'Outdoor Apparel',
    country: 'USA',
    esgScore: 92,
    environmentalScore: 95,
    socialScore: 90,
    governanceScore: 91,
    supplyChainTransparency: 94,
    carbonFootprint: 88,
    laborEthics: 93,
    trend: 'up',
    trendValue: 1.5,
    certificates: ['B Corp', 'Fair Trade', 'bluesign', 'ISO 14001'],
    lastUpdated: '2024-01-15',
    sentiment: 94,
    newsHighlights: [
      { title: 'Patagonia donates $10M to environmental causes', source: 'NYT', date: '2024-01-14', sentiment: 'positive' },
      { title: 'Worn Wear program reaches 1M repaired items', source: 'Forbes', date: '2024-01-10', sentiment: 'positive' },
    ],
    history: [
      { month: 'Aug', esg: 89, environmental: 92, social: 87, governance: 88 },
      { month: 'Sep', esg: 90, environmental: 93, social: 88, governance: 89 },
      { month: 'Oct', esg: 90, environmental: 93, social: 88, governance: 90 },
      { month: 'Nov', esg: 91, environmental: 94, social: 89, governance: 90 },
      { month: 'Dec', esg: 91, environmental: 94, social: 89, governance: 91 },
      { month: 'Jan', esg: 92, environmental: 95, social: 90, governance: 91 },
    ],
  },
  {
    id: 'hm',
    name: 'H&M',
    logo: '🧥',
    industry: 'Fast Fashion',
    country: 'Sweden',
    esgScore: 68,
    environmentalScore: 65,
    socialScore: 70,
    governanceScore: 69,
    supplyChainTransparency: 62,
    carbonFootprint: 55,
    laborEthics: 64,
    trend: 'up',
    trendValue: 2.1,
    certificates: ['ISO 14001', 'OEKO-TEX', 'BCI'],
    lastUpdated: '2024-01-14',
    sentiment: 68,
    newsHighlights: [
      { title: 'H&M Conscious Collection uses 80% recycled materials', source: 'Vogue', date: '2024-01-13', sentiment: 'positive' },
      { title: 'Greenwashing accusations from environmental groups', source: 'BBC', date: '2024-01-07', sentiment: 'negative' },
    ],
    history: [
      { month: 'Aug', esg: 62, environmental: 59, social: 64, governance: 63 },
      { month: 'Sep', esg: 63, environmental: 60, social: 65, governance: 64 },
      { month: 'Oct', esg: 64, environmental: 61, social: 66, governance: 65 },
      { month: 'Nov', esg: 65, environmental: 62, social: 67, governance: 66 },
      { month: 'Dec', esg: 66, environmental: 63, social: 68, governance: 67 },
      { month: 'Jan', esg: 68, environmental: 65, social: 70, governance: 69 },
    ],
  },
  {
    id: 'nike',
    name: 'Nike',
    logo: '👟',
    industry: 'Sportswear',
    country: 'USA',
    esgScore: 71,
    environmentalScore: 70,
    socialScore: 72,
    governanceScore: 71,
    supplyChainTransparency: 68,
    carbonFootprint: 60,
    laborEthics: 66,
    trend: 'up',
    trendValue: 1.8,
    certificates: ['ISO 14001', 'bluesign'],
    lastUpdated: '2024-01-15',
    sentiment: 72,
    newsHighlights: [
      { title: 'Nike Move to Zero initiative reduces emissions by 30%', source: 'CNBC', date: '2024-01-11', sentiment: 'positive' },
      { title: 'Flyknit technology saves 3.5M lbs of waste', source: 'TechCrunch', date: '2024-01-06', sentiment: 'positive' },
    ],
    history: [
      { month: 'Aug', esg: 65, environmental: 64, social: 66, governance: 65 },
      { month: 'Sep', esg: 66, environmental: 65, social: 67, governance: 66 },
      { month: 'Oct', esg: 67, environmental: 66, social: 68, governance: 67 },
      { month: 'Nov', esg: 68, environmental: 67, social: 69, governance: 68 },
      { month: 'Dec', esg: 70, environmental: 69, social: 71, governance: 70 },
      { month: 'Jan', esg: 71, environmental: 70, social: 72, governance: 71 },
    ],
  },
  {
    id: 'shein',
    name: 'Shein',
    logo: '👚',
    industry: 'Ultra-Fast Fashion',
    country: 'China',
    esgScore: 28,
    environmentalScore: 20,
    socialScore: 30,
    governanceScore: 34,
    supplyChainTransparency: 15,
    carbonFootprint: 18,
    laborEthics: 22,
    trend: 'down',
    trendValue: -2.5,
    certificates: [],
    lastUpdated: '2024-01-15',
    sentiment: 25,
    newsHighlights: [
      { title: 'Shein faces new scrutiny over labor practices', source: 'WSJ', date: '2024-01-14', sentiment: 'negative' },
      { title: 'Environmental impact report reveals massive waste', source: 'The Guardian', date: '2024-01-09', sentiment: 'negative' },
      { title: 'Shein pledges $50M for textile waste reduction', source: 'Reuters', date: '2024-01-03', sentiment: 'positive' },
    ],
    history: [
      { month: 'Aug', esg: 32, environmental: 24, social: 34, governance: 38 },
      { month: 'Sep', esg: 31, environmental: 23, social: 33, governance: 37 },
      { month: 'Oct', esg: 30, environmental: 22, social: 32, governance: 36 },
      { month: 'Nov', esg: 29, environmental: 21, social: 31, governance: 35 },
      { month: 'Dec', esg: 29, environmental: 21, social: 31, governance: 35 },
      { month: 'Jan', esg: 28, environmental: 20, social: 30, governance: 34 },
    ],
  },
];

export const pricingTiers: PricingTier[] = [
  {
    name: 'Ücretsiz',
    nameKey: 'free',
    price: '$0',
    priceNum: 0,
    period: '/ay',
    credits: '5 credits',
    features: [
      '5 analysis credits per month',
      'Basic ESG score breakdown',
      'Environmental score',
      'Social score',
      'Governance score',
      'Community access',
    ],
    highlighted: false,
    cta: 'Get Started Free',
  },
  {
    name: 'Pro',
    nameKey: 'pro',
    price: '$3.99',
    priceNum: 3.99,
    period: '/ay',
    credits: '50 credits',
    features: [
      '50 analysis credits per month',
      'Advanced AI-powered analysis',
      'Brand comparison mode',
      'Reliability history tracking',
      'Supply chain transparency scores',
      'Carbon footprint analysis',
      'Email notifications',
      'Priority support',
    ],
    highlighted: true,
    badge: 'Most Popular',
    cta: 'Upgrade to Pro',
  },
  {
    name: 'Elite',
    nameKey: 'elite',
    price: '$9.99',
    priceNum: 9.99,
    period: '/ay',
    credits: 'Unlimited',
    features: [
      'Unlimited analysis credits',
      'Full detailed sustainability reports',
      'PDF report export (3-page)',
      'Side-by-side brand comparison',
      'Custom watchlist alerts',
      'API access',
      'Dedicated account manager',
      'Custom integrations',
      'White-label reports',
      'Real-time monitoring',
    ],
    highlighted: false,
    badge: 'Enterprise',
    cta: 'Go Elite',
  },
];

export const watchlistItems: WatchlistItem[] = [
  { brandId: 'zara', brandName: 'Zara', addedDate: '2024-01-01', alertThreshold: 5, emailAlerts: true, lastScore: 59, currentScore: 62 },
  { brandId: 'patagonia', brandName: 'Patagonia', addedDate: '2023-12-15', alertThreshold: 3, emailAlerts: true, lastScore: 91, currentScore: 92 },
  { brandId: 'hm', brandName: 'H&M', addedDate: '2024-01-05', alertThreshold: 5, emailAlerts: false, lastScore: 66, currentScore: 68 },
  { brandId: 'shein', brandName: 'Shein', addedDate: '2024-01-10', alertThreshold: 3, emailAlerts: true, lastScore: 29, currentScore: 28 },
];

export const analysisHistory = [
  { id: 1, brand: 'Zara', date: '2024-01-15 14:30', score: 62, type: 'Deep Scan' },
  { id: 2, brand: 'Patagonia', date: '2024-01-14 10:15', score: 92, type: 'Quick Scan' },
  { id: 3, brand: 'H&M', date: '2024-01-13 16:45', score: 68, type: 'Deep Scan' },
  { id: 4, brand: 'Nike', date: '2024-01-12 09:00', score: 71, type: 'Comparison' },
  { id: 5, brand: 'LC Waikiki', date: '2024-01-11 11:20', score: 54, type: 'Quick Scan' },
  { id: 6, brand: 'Shein', date: '2024-01-10 13:00', score: 28, type: 'Deep Scan' },
  { id: 7, brand: 'Patagonia', date: '2024-01-09 15:30', score: 91, type: 'PDF Report' },
  { id: 8, brand: 'Zara', date: '2024-01-08 08:45', score: 60, type: 'Quick Scan' },
];

export const industryBenchmarks = [
  { industry: 'Outdoor Apparel', avgScore: 78 },
  { industry: 'Sportswear', avgScore: 65 },
  { industry: 'Fast Fashion', avgScore: 52 },
  { industry: 'Ultra-Fast Fashion', avgScore: 30 },
  { industry: 'Luxury', avgScore: 72 },
  { industry: 'Casual Wear', avgScore: 60 },
];

export function getScoreColor(score: number): string {
  if (score >= 80) return '#10b981';
  if (score >= 60) return '#f59e0b';
  if (score >= 40) return '#f97316';
  return '#ef4444';
}

export function getScoreLabel(score: number): string {
  if (score >= 80) return 'Excellent';
  if (score >= 60) return 'Good';
  if (score >= 40) return 'Fair';
  return 'Poor';
}
